CREATE TABLE UserActivity 
   (	UUID VARCHAR(100) NOT NULL,
		User_UUID VARCHAR(100) NOT NULL,
		Activity_UUID VARCHAR(100) NOT NULL,
		
		IS_DELETED VARCHAR(1) DEFAULT '0',
		DATE_CREATE timestamp NOT NULL,
		CREATE_BY VARCHAR(50),
		DATE_UPDATE timestamp,
		UPDATE_BY VARCHAR(50)	  )  ;
  
  CREATE UNIQUE INDEX UserActivity_UUID_PK ON UserActivity (UUID); 
  
ALTER TABLE UserActivity ADD CONSTRAINT UserActivity_UUID_PK PRIMARY KEY (UUID);
ALTER TABLE UserActivity ADD CONSTRAINT UserActivity_User_FK FOREIGN KEY (User_UUID) REFERENCES Users (User_UUID);
ALTER TABLE UserActivity ADD CONSTRAINT UserActivity_Activity_FK FOREIGN KEY (Activity_UUID) REFERENCES Activity (UUID);