CREATE TABLE Question 
   (	UUID VARCHAR(100) NOT NULL ,
        Question VARCHAR(6000),
		User_uuid VARCHAR(100) NOT NULL,

		IS_DELETED VARCHAR(1) DEFAULT '0',
		DATE_CREATE timestamp NOT NULL,
		CREATE_BY VARCHAR(50),
		DATE_UPDATE timestamp,
		UPDATE_BY VARCHAR(50)	  )  ;
  
  CREATE UNIQUE INDEX Question_UUID_PK ON Question (UUID); 
  
ALTER TABLE Question ADD CONSTRAINT Question_UUID_PK PRIMARY KEY (UUID);
ALTER TABLE Question ADD CONSTRAINT Question_User_FK FOREIGN KEY (User_uuid) REFERENCES Users (User_UUID);