CREATE TABLE Answer 
   (	UUID VARCHAR(100) NOT NULL ,
        answer VARCHAR(6000),
        question_uuid VARCHAR(100) NOT NULL,
		User_uuid VARCHAR(100) NOT NULL,

		IS_DELETED VARCHAR(1) DEFAULT '0',
		DATE_CREATE timestamp NOT NULL,
		CREATE_BY VARCHAR(50),
		DATE_UPDATE timestamp,
		UPDATE_BY VARCHAR(50)	  )  ;
  
  CREATE UNIQUE INDEX Answer_UUID_PK ON Answer (UUID); 
  
ALTER TABLE Answer ADD CONSTRAINT Answer_UUID_PK PRIMARY KEY (UUID);
ALTER TABLE Answer ADD CONSTRAINT Answer_Question_FK FOREIGN KEY (question_uuid) REFERENCES Question (UUID);
ALTER TABLE Answer ADD CONSTRAINT Answer_User_FK FOREIGN KEY (User_uuid) REFERENCES Users (User_UUID);